<?php
/**
 * Created by PhpStorm.
 * User: fy
 * Date: 16-7-20
 * Time: 下午2:37
 */

namespace Admin\Controller;


class BusinessController extends AdminController
{

    
    public function index()
    {
        parent::index(); // TODO: Change the autogenerated stub
    }

    /**
     * 添加页面
     */
    public function add()
    {
        $this->display('edit');
    }

    /**
     * 修改页面
     */
    public function edit()
    {
        $this->display('edit');
    }

    /**
     * 软删除 更新状态
     */
    public function delete()
    {

    }

    /**
     * 保存更新内容【添加|修改|软删除】
     */
    public function save()
    {

    }

    /**
     * 删除真实数据
     */
    public function remove()
    {

    }

}